### ISSUE TITLE
add examples of eval

### ISSUE THREAD

**Issue by MarcoGorelli** [MarcoGorelli/pyladieslondon-sprints#10]
This answer https://stackoverflow.com/a/53779987/4451315 gives lots of great examples, but the pandas docs are a bit scant. Can we add an example from there?

**Comment by AnglinaBhambra** [comment]
working on this

**Comment by MarcoGorelli** [comment]
closing for now , but feel free to submit what you've done so far - else I'll reopen in the main pandas repo
