### ISSUE TITLE
Function overloads

### ISSUE THREAD

**Issue by MarcoGorelli** [MarcoGorelli/pyladieslondon-sprints#29]
The issue is to use `typing.overload` to make the return type of some functions more precise.

An introductory video on `typing.overload`: https://youtu.be/rY9NZ-tXiDQ

A (work-in-progress) blog post on this topic: https://m-e-gorelli.medium.com/making-sense-of-typing-overload-437e6deecade

In the following methods all return something like `Optional[FrameOrSeries]`. We should overload them, so that if `inplace=True` they return `None` and if `inplace=False` they return `FrameOrSeries`

https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py

- [ ] drop_duplicates
- [ ] drop

https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py

- [ ] interpolate
- [ ] bfill
- [ ] ffill

- https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py

- [ ] drop_duplicates

----

From the pandas codebase, see [set_axis](https://github.com/pandas-dev/pandas/blob/9bfa67cf028deec509d4e07138f6659bd2b342fe/pandas/core/generic.py#L693-L721) and [reset_index](https://github.com/pandas-dev/pandas/blob/9bfa67cf028deec509d4e07138f6659bd2b342fe/pandas/core/frame.py#L5384-L5456) for examples

**Comment by olgarithms** [comment]
I will work on this

**Comment by MarcoGorelli** [comment]
> I will work on this

Awesome!

Which function? there's quite a few here, multiple people can work on it together, perhaps pick one to start with?

**Comment by olgarithms** [comment]
I can start with `drop_duplicates` from `series.py`.

**Comment by MarcoGorelli** [comment]
closing as this is mostly done for now, and further work is pending on https://github.com/pandas-dev/pandas/issues/41485
