### ISSUE TITLE
Add test for fixed regression in concat with categorical datetime data

### ISSUE THREAD

**Issue by jorisvandenbossche** [MarcoGorelli/pyladieslondon-sprints#32]
https://github.com/pandas-dev/pandas/issues/39443 was a regression that in the meantime is fixed. But, we still want to add a test for it, to ensure it keeps working in the future.

A test for this can be added to `pandas/tests/reshape/concat/test_categorical.py`

**Comment by MarcoGorelli** [comment]
closing so the pandas issue is the reference one
