### ISSUE TITLE
 Add test for fixed regression in concat with empty DataFrames 

### ISSUE THREAD

**Issue by jorisvandenbossche** [MarcoGorelli/pyladieslondon-sprints#33]
https://github.com/pandas-dev/pandas/issues/39037 was a regression on master that in the meantime is fixed. But, we still want to add a test for it, to ensure we don't break it again in the future.

A test for this can be added to `pandas/tests/reshape/concat/test_empty.py`

**Comment by weikhor** [comment]
Hi This pull request https://github.com/pandas-dev/pandas/pull/41677 is about adding the test for fixed regression in concat with empty DataFrames. Thank
