### ISSUE TITLE
use better example in pd.lookup replacement

### ISSUE THREAD

**Issue by MarcoGorelli** [MarcoGorelli/pyladieslondon-sprints#8]
https://github.com/pandas-dev/pandas/issues/39171#issuecomment-773477244

In the user guide, let's use
```
idx, cols = pd.factorize(df['col'])
df.reindex(cols, axis=1).to_numpy()[np.arange(len(df)), idx]
```
instead of the current workaround

https://pandas.pydata.org/pandas-docs/dev/user_guide/indexing.html#looking-up-values-by-index-column-labels

**Comment by psupp** [comment]
I will like to work on this.-- Suparna

**Comment by MarcoGorelli** [comment]
Awesome, thanks!

**Comment by MarcoGorelli** [comment]
moved to the pandas repo
